[package]
versioned_files = ["Cargo.toml", "Cargo.lock"]
changelog = "CHANGELOG.md"
assets = "artifacts/*"

[github]
owner = "WasmEdge"
repo = "wasmedgeup"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit --signoff -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "master"

[workflows.steps.title]
template = "chore: release wasmedgeup $version"

[workflows.steps.body]
template = "Merging this PR will create a new release.\n\n$changelog"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"
